services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      BINANCE_API_URL: "https://testnet.binance.vision"     # change to prod url for production
      BINANCE_API_KEY: /run/secrets/binance_api_key
      BINANCE_API_SECRET: /run/secrets/binance_api_secret
      BINANCE_COMMISSION_PCT: 0.01                          # 0.01 percents
      APP_PORT: 3000
      APP_CACHE_DURATION_MS: 10000                          # 10 sec
    ports:
      - 3000:3000
    secrets:
      - binance_api_key
      - binance_api_secret